### ISSUE TITLE
Does it actually work?

### ISSUE THREAD

**Issue by azazar** [sirhamsteralot/HaE-PBLimiter#16]
I've made a [simple busywaiting script](https://gist.github.com/azazar/81b1bac6e1116f1aeb13fb130ca02356), and it's getting stopped by SE itself, before hitting any HaE-PBLimiter triggers. Does HaE-PBLimiter actually kill PBs that cause high server load? Did you compare game server performance with and without it? Does is do anything but delivery of pita to SE players?

**Comment by KuroshiShirone** [comment]
Yes, yes and yes. It does exactly what it describes to be doing

**Comment by sirhamsteralot** [comment]
Scripts execute in the game thread, you can make a many executions busywait script that takes practically no performance and get stopped by SE or you can make a couple execution script that locks up the game for a second. All my plugin does is measure the actual real world performance a script has and takes action based upon that. (AKA murder them if they are too slow because a single script can absolutely destroy simspeed).
