### ISSUE TITLE
How about rewarding PB for good behavior?

### ISSUE THREAD

**Issue by Starwaster** [sirhamsteralot/HaE-PBLimiter#35]
Subject says it all really.

Even really well written and well behaved scripts WILL burn down their PB given enough time. The reason it happens is the server itself suffering performance drops that cause the script to exceed its runtime limit rather than the other way around. 

Literally the server taking longer to process a scripts instructions than it usually would for the Same set of instructions. 

So how about rewarding the PB (and/or player) for times the PB was under limits? If the threshold is 0.3ms and 90% of the time it’s 0.008 then periodically remove a penalty instead of waiting for server reset to clear them all. 

It would be like the PB cooling down

**Comment by sirhamsteralot** [comment]
This could be an interesting idea, sadly i havent had much time at all recently due to being busy with my studies anb honestly havent been bothering with SE much at all other than keeping my plugins working but ill keep it in mind. Although the sensitivity field in the pb is already doing this sortof, when the significance is lower then that means that the more recent ticks count less against the pbs history so theoretically a lower ticksignificance will mean an average that is harder to move about the .3ms treshold

**Comment by sirhamsteralot** [comment]
Having thought about it for 4 whole years i dont think this is a good change as it would allow people to cheese the system by just having pbs that do essentially nothing for a long time to then start lagging the server. and as stated earlier it is already implemented in a way with the exceptions and leniency built in to the averaging
